spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: chirayu
    password: chirayu
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
server:
  port: 8053
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"

